from function_tests import functions_for_Q1_to_Q4_tests as fT
from function_tests import functions_for_Q5_to_Q20_tests as fT2

#print("\n\nFirst test: \n")
#func_test1 = fT.first_method_test()
#print("\n\nSecond test: \n")
#func_test2 = fT.second_method_test()
#print("\n\nThird test: \n")
#func_test3 = fT.third_method_test()
#print("\n\nForth test: \n")
#func_test4 = fT.forth_method_test()
#print("\n\nFifth test: \n")
#func_test5 = fT2.fifth_method_test()
#print("\n\nSixth test: \n")
#func_test6 = fT2.sixth_method_test()
#print("\n\nSeventh test: \n")
#func_test7 = fT2.seventh_method_test()
#print("\n\nEighth test: \n")
#func_test8 = fT2.eighth_method_test()
#print("\n\nNinth test: \n")
#func_test9 = fT2.ninth_method_test()
#print("\n\nThirteenth test: \n")
#func_test13 = fT2.thirteenth_method_test()
#print("\n\nFourteenth test: \n")
#func_test14 = fT2.fourteenth_method_test()
#print("\n\nFifteenth test: \n")
#func_test15 = fT2.fifteenth_method_test()
#print("\n\nSixteenth test: \n")
#func_test16 = fT2.sixteenth_method_test()
#print("\n\nSeventeenth test: \n")
#func_test17 = fT2.seventeenth_method_test()
#print("\n\nEighteenth test:\n")
#func_test18 = fT2.eighteenth_method_test()
#print("\n\nNineteenth test: \n")
#func_test19 = fT2.nineteenth_method_test()
print("\n\nTwentieth test: \n")
funct_test20 = fT2.twentieth_method_test()
